language: python
python:
  - 2.7
  - 3.5
  - 3.6

# For Python 3.7
matrix:
  include:
    - python: 3.7
      dist: xenial
      sudo: true

  allow_failures:
    - python: 2.7

script:
  - python setup.py install
  - python test.py
